   export const spanishData = {
        ui: {
          addPlayer: "Añadir Jugador",
          startGame: "Comenzar",
          settings: "Configuración",
          questionsTab: "Preguntas",
          rouletteTab: "Ruleta",
          punishmentsTab: "Castigos",
          minigamesTab: "Minijuegos",
          questionsOther : "Preguntas Incomodas",
          addQuestion: "Añadir Pregunta",
          addPunishment: "Añadir Castigo",
          addMinigame: "Añadir Minijuego",
          add: "Añadir",
          spin: "Girar",
          editQuestion: "Editar Pregunta",
          editPunishment: "Editar Castigo",
          editMinigame: "Editar Minijuego",
          update: "Actualizar",
          cancel: "Cancelar",
          resetDefaults: "Resetear a Predeterminados",
          deleteElement: "¿Seguro que quieres eliminar este elemento?",
          requiresPeople: "¿Requiere otro jugador?",
          requiresNone: "Nadie",
          requiresOppositeGender: "Género Opuesto",
          requiresAny: "Cualquier Jugador",
          confirmation: "¿Estás seguro?",
          yes: "Sí",
          no: "No",
          noQuestions: "No hay preguntas. ¡Añade algunas!",
          noRouletteItems:
            "La ruleta está vacía. ¡Añade items en la configuración!",
          playerListPlaceholder: "Añade de 2 a más jugadores",
          addPlayersPlaceholder: "Nombre del jugador",
          male: "HOMBRE",
          female: "MUJER",
          addQuestionPlaceholder: "Escribe la pregunta...",
          addPunishmentPlaceholder: "Escribe el castigo...",
          addMinigamePlaceholder: "Describe el minijuego...",
          with: "con",
          noOppositeGender:
            "(pero no hay nadie del otro género, ¡te salvaste!)",
          noOtherPerson: "(pero no hay nadie más, ¡te salvaste!)",
          questionHeader: "La pregunta es para todos:",
          rouletteHeader: "¡{playerName}, tu destino te espera!",
          choosePlayerPrompt:
            "El grupo elige al jugador más votado y presiona el botón.",
          playerChosenBtn: "ELEGIR JUGADOR",
          continueBtn: "LISTO",
          activeRule: "Regla Activa",
          selectPlayerTitle: "¿Quién fue el elegido?",
          cardPunishment: "Castigo",
          cardMinigame: "Minijuego",
          cardRule: "Regla",
          cardLuck: "Suerte",
          cardNoLuck: "Mala Suerte",
          cardQuestion: "Pregunta", 
          createRule: "Crea una nueva regla:",
          activeRulesTitle: "Reglas Activas",
          clearRules: "Borrar Reglas Activas",
          reSpinHeader: "¡Gira de nuevo!", // Nuevo texto para la carta de suerte
          ruleCardDescription: "¡REGLA! Tienes el poder. Crea una nueva regla que todos deban seguir.",
          luckCardDescription: "¡SUERTE! Te has salvado. Elige a otra persona para que gire la ruleta en tu lugar.",
          NoluckCardDescription: "!Mala Suerte! Bebe un trago y vuelve a girar la ruleta",
          answerQuestionsPrompt: "tienes que responder", // Nuevo
          choosePlayerForQuestionPrompt: "elige a un jugador para responder", // Nuevo
          random: "Aleatorio", // Nuevo
          nonRandom: "El jugador responde", // Nuevo
          chosetoRespond: "tienes que responder:",
          NoRespondC: "(Sino no respondes, bebes 2 tragos)"
        },
        questions: [
          "¿Quién es más probable que se ría en un momento serio?",
          "¿Quién se gastaría todo su sueldo en un día?",
          "¿Quién sobreviviría a un apocalipsis zombie?",
        ],
        answerQuestions: [ // NUEVA SECCIÓN: Preguntas para un jugador específico
         {text: "¿Cuál es la cosa más extraña que has comido?",},
          {text: "¿Si pudieras tener un superpoder, cuál sería?",},
          {text: "¿Cuál ha sido tu momento más vergonzoso?",random: true},
          {text: "¿A quién de los aquí presentes admiras más y por qué?",},
          {text: "¿Qué es lo que más te asusta?",random: true},
          {text: "¿Qué cambiarías de tu vida si pudieras volver al pasado?",},
        ],
        punishments: [
          { text: "Bebe 2 tragos" },
          { text: "Cuenta un secreto vergonzoso" },
          { text: "Baila 30 segundos sin música" },
          {
            text: "Bésate con alguien del sexo opuesto",
            requiresOppositeGender: true,
          },
        ],
        minigames: [
          { text: "El suelo es lava. ¡El último en subirse a una silla bebe!" },
          {
            text: "Categorías. Elige una categoría y di una palabra por turnos. El primero que falle, bebe.",
          },
        ],
      };

      // Data para la interfaz de usuario en inglés
      export const englishData = {
        ui: {
          addPlayer: "Add Player",
          startGame: "Start",
          settings: "Settings",
          questionsTab: "Questions",
          rouletteTab: "Roulette",
          punishmentsTab: "Punishments",
          minigamesTab: "Minigames",
          questionsOther : "Awkward Questions",
          addQuestion: "Add Question",
          addPunishment: "Add Punishment",
          addMinigame: "Add Minigame",
          add: "Add",
          spin: "Spin",
          editQuestion: "Edit Question",
          editPunishment: "Edit Punishment",
          editMinigame: "Edit Minigame",
          update: "Update",
          cancel: "Cancel",
          resetDefaults: "Reset to Defaults",
          deleteElement: "Are you sure you want to delete this item?",
          requiresPeople: "Requires another player?",
          requiresNone: "Nobody",
          requiresOppositeGender: "Opposite Gender",
          requiresAny: "Any Player",
          confirmation: "Are you sure?",
          yes: "Yes",
          no: "No",
          noQuestions: "No questions. Add some!",
          noRouletteItems: "The roulette is empty. Add items in settings!",
          playerListPlaceholder: "Add 2 or more players",
          addPlayersPlaceholder: "Player name",
          male: "MALE",
          female: "FEMALE",
          addQuestionPlaceholder: "Write the question...",
          addPunishmentPlaceholder: "Write the punishment...",
          addMinigamePlaceholder: "Describe the minigame...",
          with: "with",
          noOppositeGender:
            "(but there's no one of the opposite gender, you're safe!)",
          noOtherPerson: "(but there's nobody else, you're safe!)",
          questionHeader: "This question is for everyone:",
          rouletteHeader: "{playerName}, your destiny awaits!",
          choosePlayerPrompt:
            "The group chooses the most voted player and presses the button.",
          playerChosenBtn: "CHOOSE PLAYER",
          continueBtn: "DONE",
          activeRule: "Active Rule",
          selectPlayerTitle: "Who was chosen?",
          cardPunishment: "Punishment",
          cardMinigame: "Minigame",
          cardRule: "Rule",
          cardLuck: "Luck",
          cardNoLuck: "Bad Luck",
          cardQuestion: "Question", 
          createRule: "Create a new rule:",
          activeRulesTitle: "Active Rules",
          clearRules: "Clear Active Rules",
          reSpinHeader: "Spin again!", // New text for the luck card
          ruleCardDescription: "RULE! You have the power. Create a new rule that everyone must follow.",
          luckCardDescription: "LUCK! You're safe. Choose another person to spin the roulette wheel in your place.",
          NoluckCardDescription: "Bad Luck! Take a sip and spin the wheel again.",
          answerQuestionsPrompt: "you have to answer", // New
          choosePlayerForQuestionPrompt: "choose a player to answer", // New
          random: "Random", // New
          nonRandom: "Player Responds", // New
          chosetoRespond: "You have to answer:",
          NoRespondC: "(If you don't answer, you drink 2 sips)"
        },
        questions: [
          "Who is most likely to laugh at a serious moment?",
          "Who would spend their entire salary in one day?",
          "Who would survive a zombie apocalypse?",
        ],
        answerQuestions: [
          { text: "What is the weirdest thing you've ever eaten?" },
          { text: "If you could have one superpower, what would it be?" },
          { text: "What has been your most embarrassing moment?", random: true },
          { text: "Who among those present do you admire most and why?" },
          { text: "What are you most afraid of?", random: true },
          { text: "What would you change about your life if you could go back in time?" },
        ],
        punishments: [
          { text: "Drink 2 sips" },
          { text: "Tell an embarrassing secret" },
          { text: "Dance 30 seconds without music" },
          {
            text: "Kiss someone of the opposite gender",
            requiresOppositeGender: true,
          },
        ],
        minigames: [
          { text: "The floor is lava. The last one to get on a chair drinks!" },
          {
            text: "Categories. Choose a category and say a word in turns. The first to fail, drinks.",
          },
        ],
      };